Feature/admin
fey/TaskManager pull request #11
Opened 2021-08-15 05:34 UTC by fey

2021-08-18 19:12 UTC, greybutton requested changes

2021-08-18 19:12 UTC, greybutton commented on app/controllers/admin/application_controller.rb
> +  class Admin::ApplicationController < ApplicationController
чот здесь задвоилось

2021-08-18 19:12 UTC, greybutton commented on app/views/admin/users/edit.html.slim
> +  = render partial: "form", locals: {f: f}
форма немного разорванной получается, можно весь симпл форм убрать в _form и прокидывать из edit/new нужный url

2021-08-18 19:36 UTC, fey commented on app/controllers/admin/application_controller.rb
> +  class Admin::ApplicationController < ApplicationController
fixed

2021-08-18 19:36 UTC, fey commented on app/views/admin/users/edit.html.slim
> +  = render partial: "form", locals: {f: f}
Fixed

2021-08-19 18:37 UTC, greybutton approved these changes

2021-08-19 19:29 UTC, merged