add react
fey/TaskManager pull request #16
Opened 2021-09-07 13:11 UTC by fey

2021-09-07 16:11 UTC, greybutton requested changes

2021-09-07 16:11 UTC, greybutton commented on config/webpack/environment.js
> +environment.loaders.delete('nodeModules');
это нужно сделать до экспорта

2021-09-08 02:22 UTC, fey commented on config/webpack/environment.js
> +environment.loaders.delete('nodeModules');
fixed

2021-09-08 17:04 UTC, greybutton approved these changes

2021-09-13 19:25 UTC, merged