add tasks states
fey/TaskManager pull request #6
Opened 2021-08-15 02:11 UTC by fey

2021-08-16 19:02 UTC, greybutton requested changes
пропустил `transition ready_for_release: :released`

2021-08-16 19:02 UTC, greybutton commented on app/models/task.rb
> +  state_machine :initial => :new_task do
проверь плис рубокоп, вроде он на такое исправить может `initial: :new_task`

2021-08-16 19:02 UTC, greybutton commented on app/models/task.rb
> +      transition :in_code_review => :in_development
можно `transition [:in_qa, : in_code_review] => : in_development`

полная дока https://github.com/pluginaweek/state_machine

2021-08-17 18:09 UTC, fey commented
@greybutton поправил замечания

2021-08-17 19:11 UTC, greybutton approved these changes

2021-08-17 19:11 UTC, greybutton commented on app/models/task.rb
> +      transition [in_qa, in_code_review] => :in_development
вроде надо двоеточия добавить перед названиями стейтов

2021-08-18 19:10 UTC, fey commented on app/models/task.rb
> +      transition [in_qa, in_code_review] => :in_development
Блин, действительно. Линтер промолчал(( 
Поправил

2021-08-18 19:11 UTC, merged